apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/cuhealthai-foundations/docker-repo/hello:latest
          env:
            - name: TARGET
              value: "Python Sample v2"
            - name: PORT
              value: "8080
