# github action for linting using dagger
# referenced from https://github.com/dagger/dagger-for-github
---
name: dagger lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Dagger
        uses: dagger/dagger-for-github@v2
        with:
          cmds: do lint
