name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  notebook-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: "3.8"
      - name: Running the notebook
        shell: bash -l {0}
        run: |
          conda list
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi          
          python -m ipykernel install --user --name python3
          cd src/Notebooks
          echo "Running the notebook..."
          papermill -k python3 --log-output "Create Cites from PMC Lookups.ipynb" -
