name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  notebook-1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: python3

      - name: Create kernelspec
        shell: bash -l {0}
        run: |
          conda activate python3
          conda install jupyter
          jupyter kernelspec install --user --name python3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run the notebook(s)
        run: |
          cd src/Notebooks
          papermill -k python3 --log-output "Create Cites from PMC Lookups.ipynb" -
