name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Create kernelspec
        run: |
          jupyter kernelspec install --name python3
      - name: Run the notebook(s)
        run: |
          cd src/Notebooks
          papermill -k python3 --log-output "Create Cites from PMC Lookups.ipynb" -
